### ISSUE TITLE
とても助かるツール、ありがとうございます。不躾ながら要望を書いてもよろしいでしょうか

### ISSUE THREAD

**Issue by icesou** [raon555/Shiny-Colors-STEP-maximum-simulator#1]
要望1
スプレッドシートで管理したいので「累計特化上限成長回数:なんとか」と「残り熟練度：なんとか」の間のコロンを半角で統一してほしい

要望2
「一回目のシュミレーション結果による残り団結力」から「団結力SP変換」を行ったのち、二回目のシュミレーションをおこなうわけですが、一回目のシュミレーション結果に次の値も記してくれると助かります

「団結力SP変換」後団結力残高として
現在の団結力-「一回目のシュミレーション結果による残り団結力」

及び何回SP変換できるか
quotient(「一回目のシュミレーション結果による残り団結力」,30)

及び搾り取れるSP量
(quotient(「一回目のシュミレーション結果による残り団結力」,30))*10

ここまで読んでくれてありがとうございました。

**Comment by raon555** [comment]
修正しました。
コメントして頂き、ありがとうございます
