### ISSUE TITLE
WindowsFormへのリプレイス

### ISSUE THREAD

**Issue by ado-shi** [raon555/Shiny-Colors-STEP-maximum-simulator#3]
僭越ではありますがご報告まで。
めちゃくちゃ便利なアプリがある！と思いこちらを覗かせていただいたところ、
> 他言語へのリプレイスも歓迎です

との記載が目に入ったので、弱輩ながら、C#の学習も兼ねてWindowsFormにリプレイスさせていただきました。
https://github.com/ado-shi/Shiny-Colors-STEP-maximum-simulator/tree/develop_winForm
![2022y07m12d_010432270](https://user-images.githubusercontent.com/109031310/178308639-a9d33e80-5bf3-4439-874c-20c1d31971f5.jpg)

ロジック部分をほぼ丸々移植しておりますので、もし公開他、問題がありましたら、コメントいただけると幸いです。その際はリポジトリ毎削除いたします。

**Comment by raon555** [comment]
おお！めちゃくちゃ良いですね！
GUI版も作りたいなと思いつつもあまり知見がなく、改修ハードルが高かったのですが
めちゃくちゃ良いものを作っていただいた上に公開までしていただけるとは......ありがとうございました！

公開や自分が作りました～！的な宣伝等も特に問題ありません。
よろしくお願いいたします。
